### ISSUE TITLE
rosatta giving error POEntry object is not JSON serializable with Django 1.6.5

### ISSUE THREAD

**Issue by humpfreybogart** [mbi/django-rosetta#106]
Hello and thank You for a great tool

I'm having trouble though using rosetta with Django 1.6.5

When I click on the language file I want to translate, I get the following error
TypeError at /rosetta/select/da-dk/0/
POEntry object at 0x7f2a29b602d0> is not JSON serializable

Please help

Thank You

**Comment by mbi** [comment]
Hmm, could you please:
-  Share the PO file that exposes this issue?
- What are your Rosetta-related settings and what is settings.CACHES? 
- Running on devserver / fastcgi / gunicorn / mod_wsgi / … ?
- Which version of Rosetta? (HEAD, point-release?)
- And finally, what is the output of `pip freeze`

**Comment by humpfreybogart** [comment]
Hi 

Thank You for helping me.

Here are the answer to most of Your questions 
https://github.com/michaelhjulskov/rosetta

Which version of Rosetta? (HEAD, point-release?)
Running on devserver / fastcgi / gunicorn / mod_wsgi / … ? (I run it through Pycharm on my local linux)
Im sorry I dont know the answer to those two. 
Please ask again if You still need this.

Forgive I am a newbie, but I'm trying my best!
Thank You

**Comment by humpfreybogart** [comment]
By the way as soon as I empty the po file it doesnt shout out the error.

**Comment by humpfreybogart** [comment]
Hi after I went back to the original po file, and it worked until i saved. I got the same error again, but I can see my changes have been saved to the po file. so in a way it works, but its shouting the error everytime I save.

**Comment by mbi** [comment]
Okay, I see what is going on, but I can't really fix because of the way Django handles sessions in version 1.6

One solution would be to stop using the SessionStorage, and use the CacheStorage instead in your settings:

`ROSETTA_STORAGE_CLASS = 'rosetta.storage.CacheRosettaStorage'`

Make sure you have a proper & valid cache server (e.g. memcache) and you'll be fine.

**Comment by humpfreybogart** [comment]
YES Marco :-D

Thank You VERY MUCH for helping with this - I wiil share to other
django-oscar users

It works perfectly now

Michael

**Comment by rafaelro** [comment]
tried 
ROSETTA_STORAGE_CLASS = 'rosetta.storage.CacheRosettaStorage'
and i get same PO Json error

changed to ( as per docs ) 
ROSETTA_CACHE_NAME = 'rosetta.storage.CacheRosettaStorage'

and:
Django Version: 1.6.5
Exception Type: InvalidCacheBackendError
Exception Value:  
Could not find backend 'rosetta.storage.CacheRosettaStorage': Could not find backend 'rosetta.storage.CacheRosettaStorage': Could not find backend 'rosetta.storage.CacheRosettaStorage': Could not find backend 'rosetta.storage.CacheRosettaStorage': Module "rosetta.storage" does not define a "CacheRosettaStorage" attribute/class

any ideas ?
