### ISSUE TITLE
Rosetta views broken by Django 1.7 expected behaviour

### ISSUE THREAD

**Issue by artscoop** [mbi/django-rosetta#107]
Hi,
Clicking the "_next" button to translate a block in Django 1.7 runserver poses a problem. 

Django 1.7 docs state that "In addition, the development server automatically reloads when a translation file is updated, i.e. after running compilemessages."

That is, when you click the button, it processes the locale files, which kills and restarts the server before letting Rosetta process the rest of the view.

I don't know what to do with this. Maybe request an option to exclude files to check for a reload in Django's runserver command...

The runserver --noreload obviously fixes the problem, but --noreload is not a preferred way of using runserver.

**Comment by mbi** [comment]
Hello, 

I'm having a hard time trying to reproduce this. I'm testing with Django 1.7b4, and 60 messages PO file: the devserver _is_ restarted, but only after the request was completed and a proper response (plus redirection) is returned, am I missing something here?

```
[19/Jun/2014 02:37:41] "POST /rosetta/?page=1 HTTP/1.1" 302 0
[19/Jun/2014 02:37:41] "GET /rosetta/?_next=1&page=1&_next=1 HTTP/1.1" 302 0
[19/Jun/2014 02:37:41] "GET /rosetta/?page=2 HTTP/1.1" 200 20509
Performing system checks...

System check identified no issues (0 silenced).
June 19, 2014 - 02:37:42
Django version 1.7b4, using settings 'testproject.settings'
Starting development server at http://0.0.0.0:8000/
```

**Comment by artscoop** [comment]
I'm wondering: Do you have Linux and ipynotify installed ?
The behaviour (which is by Django 1.7 design) was confirmed in this ticket: https://code.djangoproject.com/ticket/22857

**Comment by mbi** [comment]
Hmm, nope, sorry I'm developing on a Mac. Does this issue depend on this environment? I could spin up a VM if need be.

**Comment by artscoop** [comment]
No problem for me. Don't bother, it seems that the "bug" only occurs in Linux with pyinotify installed. As stated in the docs:

> On Linux systems, if pyinotify is installed, the development server will reload immediately when a file 
> is changed. Previously, it polled the filesystem for changes every second. That caused a small delay 
> before reloads and reduced battery life on laptops.
> In addition, the development server automatically reloads when a translation file is updated, i.e. after
> running compilemessages.

Which is why POST views don't even finish processing.
I opened a ticket in Django which was accepted.

**Comment by mbi** [comment]
Ah, good catch. I'll update the docs with a warning and a link to the release notes.
