### ISSUE TITLE
Release to PyPI?

### ISSUE THREAD

**Issue by amandasaurus** [mbi/django-rosetta#108]
I see the code on github is 0.7.5 ( as of https://github.com/mbi/django-rosetta/commit/68e02a3094a53b4e7bbb2ace0226ba0863257ca9 ), but the version on PyPI is 0.7.4 ( https://pypi.python.org/pypi/django-rosetta ). Would it be possible to make a software release so I could install 0.7.5 via pip/pypi?

**Comment by mbi** [comment]
Hello. I was planning to release a point release on PyPI when Django 1.7 is released.
In the meantime you could install 0.7.5 directly from Github: 

`pip install https://github.com/mbi/django-rosetta/archive/develop.zip`

Would this be an option?

**Comment by amandasaurus** [comment]
Yeah that's good enough for me now. You are clearly aware of the issue.

I would like if there was a 0.7.5 version available that didn't require Dj1.7. 0.7.4 has a bug when using ajax suggest on https sites (fixed here https://github.com/mbi/django-rosetta/commit/2ad3f83e61d81d2d60a52a1cfb86efae9d77e3dc ). It would be nice to have a proper version usable without needing to upgrade django.

**Comment by mbi** [comment]
## Sure: Rosetta supports django stable and the two previous versions, plus django's LTS version if possible.  

Marco Bonetti
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by amandasaurus** [comment]
That's OK then. That resolves the issue.
