### ISSUE TITLE
Rosetta should display gettext message context

### ISSUE THREAD

**Issue by vdboor** [mbi/django-rosetta#111]
The getext message context (`msgctxt`) field provides valuable information to translators. It would be really helpful if Rosetta also displays this value, and possibly even allows filtering on it.

Currently I'm using this to filter between admin and non-admin texts, but this information can't be find anywhere in rosetta.

**Comment by mbi** [comment]
Hi, sorry for the delay. Rosetta DOES display `msgctxt` messages and has been ages, am I missing something here?
