### ISSUE TITLE
Azure translation suggestion error

### ISSUE THREAD

**Issue by nordbit** [mbi/django-rosetta#112]
`TranslateApiException: Cannot find an active Azure Market Place Translator Subscription associated with the request credentials. : ID=3944.V2_Json.Translate.2139BE4D`

Sometimes work, most of cases not

**Comment by dmitry** [comment]
@nordbit any news?

**Comment by svdvonde** [comment]
@mbi You can probably close this issue as well?

**Comment by mbi** [comment]
Yup, thanks.
