### ISSUE TITLE
Rosetta crashes when used with a custom Djagno user lacking a first_name, last_name or email setter

### ISSUE THREAD

**Issue by stevejalim** [mbi/django-rosetta#114]
The code here 

```
https://github.com/mbi/django-rosetta/blob/develop/rosetta/views.py#L145 
...
        # Provide defaults in case authorization is not required.
        request.user.first_name = getattr(request.user, 'first_name', 'Anonymous')
        request.user.last_name = getattr(request.user, 'last_name', 'User')
        request.user.email = getattr(request.user, 'email', 'anonymous@user.tld')
```

assumes that request.user has settable fields. However, a model based on https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser may not have them available to set (in my case, the custom user model in my web app is a wrapper for data at the other end of a service call)

Is it possible to make these fail gracefully, please? For now, I've forced my CustomUser to pretend to have those three setters (as no-ops).

**Comment by mbi** [comment]
Okay, should be fixed in 19a2e7e, thanks for spotting and reporting this!
