### ISSUE TITLE
Match makemessages and django-rosetta output

### ISSUE THREAD

**Issue by cabello** [mbi/django-rosetta#120]
Hi, when I use django-rosetta with the default `ROSETTA_POFILE_WRAP_WIDTH` the resulting `po` file is _slightly_ different from the `makemessages` command, for example:

```
-"Vous êtes à la recherche d'une page qui n'existe pas pour le moment. Cliquez "
-"sur Précédent ou posez une question sur"
+"Vous êtes à la recherche d'une page qui n'existe pas pour le moment. Cliquez"
+" sur Précédent ou posez une question sur"
```

I also tried `--no-wrap` and `ROSETTA_POFILE_WRAP_WIDTH=0` but then the comments are different:

```
-#: foo/templates/bar.html:80
-#: foo/templates/bar.html:117
+#: foo/templates/bar.html:80 foo/templates/bar.html:117
```

I also tried `ROSETTA_POFILE_WRAP_WIDTH=79` thinking it was a one-off problem but the outputs didn't match.

Is there a configuration or parameters that make `makemessages` output match `django-rosetta` output? That would be very helpful because this file usually results in conflicts due to the big changes.

I am using:
- Django (1.6.9)
- django-rosetta (0.7.4)
- polib (1.0.4)

Thanks!

**Comment by mbi** [comment]
Hi. 

Good point. As a matter of fact, Django's `makemessages` uses gettext to generate the PO catalog, while Rosetta uses `polib`, hence the difference. Any idea, @izimobil ?

**Comment by izimobil** [comment]
Hi there !

Yep, @mbi is right, polib uses the python textwrap module to wrap lines while django uses gettext. This is a know issue in polib that I closed as "won't fix" some time ago, mainly because I don't have the time to dig into it: https://bitbucket.org/izi/polib/issue/50/line-wrap-improvement

Anyway feel free to reopen the bug, maybe there is a simple way to fix this issue.

Regards.

**Comment by mbi** [comment]
Thank you for the insight @izimobil. I guess I'll also close this as it's really something that ought to be handled in polib, if any. 

![hot-potato](https://cloud.githubusercontent.com/assets/131808/5972571/1c4c214a-a85c-11e4-9d5e-2096ac83ff6c.jpg)

**Comment by izimobil** [comment]
ah ah :)

**Comment by cabello** [comment]
I don't know if there is one already, but a suggestion would be: have a django-rosetta command that do what makemessages do but with polib. This way I could tell everyone:
- We are using django-rosetta for translations, when you have new translations strings or changed the original, please run: `./manage.py rosetta-makemessages -a [-d djangojs]` Everything else just visit `/rosetta` and update the translations.

**Comment by izimobil** [comment]
A better solution IMHO, would be that you connect a callback to rosetta.signals.post_save, and just call the makemessages django management command (that will reformat the pofile) for the given language code. I have not tested that ! but I think it's a good start. @mbi will probably know if it could work.
