### ISSUE TITLE
Doesn't work over HTTPS

### ISSUE THREAD

**Issue by rchernobelskiy** [mbi/django-rosetta#123]
Chrome refuses to load "http://www.google.com/jsapi" when the main site is loaded with HTTPS
Please change it to "//www.google.com/jsapi" in templates/rosetta/base.html
That automatically uses the same protocol as the main site and fixes the issue.
Thanks.

**Comment by mbi** [comment]
Yes, this has been fixed here 2ad3f83e61d81d2d60a52a1cfb86efae9d77e3dc 
It's about time I release a new version :smirk:

**Comment by rchernobelskiy** [comment]
Looking forward to the new version, thank you!
