### ISSUE TITLE
Rosetta fail with Template_debug = False

### ISSUE THREAD

**Issue by masterdubs** [mbi/django-rosetta#129]
It will give error 500 when template debug=True

Here is my settings : 

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',

```
}
```

}
# Rosetta

ROSETTA_MESSAGES_PER_PAGE = 50
ROSETTA_REQUIRES_AUTH = True
SESSION_COOKIE_SECURE = False
ROSETTA_STORAGE_CLASS = 'rosetta.storage.CacheRosettaStorage'
ROSETTA_MESSAGES_SOURCE_LANGUAGE_CODE = 'fr'
ROSETTA_MESSAGES_SOURCE_LANGUAGE_NAME = 'Français'

**Comment by mbi** [comment]
Full stacktrace, please?

**Comment by masterdubs** [comment]
Apache, Centos7 , postgres and SSL
grapelli in admin

**Comment by masterdubs** [comment]
INSTALLED_APPS = (
    'grappelli',

```
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.sites',
'service',
'accounts',
'userena',
'guardian',
'easy_thumbnails',
'modeltranslation',
 'cart',
'dashboard',
'sorl.thumbnail',
'ratings',
'paypal.standard.ipn',
'crispy_forms',
'django_extensions',
'request',
'welcome',
'billing',
#'hijack',
#'compat',
'paypalrestsdk',
'postman',
'notifications',
'knowledge',
'django_comments',
'mptt',
'tagging',
```

  #  'zinnia_bootstrap',
    'zinnia',
    'ckeditor',
    'zinnia_ckeditor',
   # 'django_nyt',
   'robots',
   'marketing',

### helpdesk

   'bootstrapform',
   'markdown_deux',
   'django.contrib.humanize',
   'helpdesk',
   'django_social_share',

### traduction

   'rosetta',
)

AUTHENTICATION_BACKENDS = (
    'userena.backends.UserenaAuthenticationBackend',
    'guardian.backends.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'userena.middleware.UserenaLocaleMiddleware',
    'request.middleware.RequestMiddleware',
    'django.middleware.locale.LocaleMiddleware',
)

ROOT_URLCONF = 'cooker.urls'

WSGI_APPLICATION = 'cooker.wsgi.application'

TEMPLATE_CONTEXT_PROCESSORS += (
     "django.core.context_processors.i18n",
     'django.core.context_processors.request',
     'django_facebook.context_processors.facebook',
)

**Comment by mbi** [comment]
Thanks, but I really need the full python traceback of the error

**Comment by masterdubs** [comment]
Not so much : 

[31/Mar/2015 18:46:39] "GET /rosetta HTTP/1.1" 301 0
[31/Mar/2015 18:46:39] "GET /rosetta/ HTTP/1.1" 200 5538
[31/Mar/2015 18:46:40] "GET /static/admin/css/forms.css HTTP/1.1" 404 4979
[31/Mar/2015 18:46:40] "GET /static/admin/css/base.css HTTP/1.1" 404 4979
[31/Mar/2015 18:46:40] "GET /static/admin/css/changelists.css HTTP/1.1" 404 4979
[31/Mar/2015 18:46:43] "GET /rosetta/?filter=third-party HTTP/1.1" 302 0
[31/Mar/2015 18:46:43] "GET /rosetta/pick/ HTTP/1.1" 500 5053
[31/Mar/2015 18:46:43] "GET /static/zinnia/theme/css/print.css HTTP/1.1" 404 4979
[31/Mar/2015 18:46:43] "GET /static/zinnia/theme/css/screen.css HTTP/1.1" 404 4979
[31/Mar/2015 18:46:43] "GET /static/zinnia/theme/img/help.png HTTP/1.1" 404 4979

and on url /rosetta/ : 
[31/Mar/2015 18:48:18] "GET /rosetta/ HTTP/1.1" 500 5053
[31/Mar/2015 18:48:18] "GET /static/zinnia/theme/css/screen.css HTTP/1.1" 404 4979
[31/Mar/2015 18:48:18] "GET /static/zinnia/theme/css/print.css HTTP/1.1" 404 4979
[31/Mar/2015 18:48:18] "GET /static/zinnia/theme/img/help.png HTTP/1.1" 404 4979

**Comment by mbi** [comment]
No no, it looks something like this. Please hit the "copy and paste view" link, then [create a gist](https://gist.github.com/) and paste its url here. Thanks. 

![sentry3](https://cloud.githubusercontent.com/assets/131808/7002761/2d8be0bc-dc50-11e4-8187-c3d751c30afd.png)

**Comment by masterdubs** [comment]
Hi, 
I find the error , in settings I write 'Français' and we need to convert it to unicode so it will be u'Français' .
Thank you for your help
