### ISSUE TITLE
Submit button doesn't redirect to next page

### ISSUE THREAD

**Issue by fetzig** [mbi/django-rosetta#13]
The "Save and translate next block" saves but doesn't bring me to the next page.

pretty obvious, so i thought it was my fault. but i debugged the code and i'm pretty sure now...its a bug.

i'm using django-rosetta 0.6.2 and django-trunk.

regards,
klemens

**Comment by fetzig** [comment]
same issue if i switch to rosetta HEAD

**Comment by fetzig** [comment]
might be a good idea to add the "_next" param to the query_ars which are added to the redirect url in https://github.com/mbi/django-rosetta/blob/develop/rosetta/views.py#L176

after that the paginator can figure out what to do in the 2nd request

**Comment by mbi** [comment]
Fixed, finally, thank you!
