### ISSUE TITLE
pt_br and pt_BR on rosetta

### ISSUE THREAD

**Issue by HomemBravo** [mbi/django-rosetta#141]
in my locale I only have pt_BR; however, when I access rosetta i find pt_br and pt_BR there; any clarification of some sort or something I am doing incorrect?

Kind regards

**Comment by mbi** [comment]
Nothing wrong probably, both forms are accepted.

Do you have the same apps / catalogs for the two locale strings? Also, is the server running on a case insensitive filesystem (e.g. Mac OS X)?
