### ISSUE TITLE
bs-Cyrl-BA

### ISSUE THREAD

**Issue by felarov** [mbi/django-rosetta#142]
django-rosetta crashes for bs-Cyrl-BA.   

rosetta/poutil.py", line 146, in find_pos
    _l, _c = map(lambda x: x.lower(), lang.split(u'-'))
ValueError: too many values to unpack

**Comment by mbi** [comment]
Yes, that would be expected. Fix should be fairly easy, I'll take a look at this tomorrow.

**Comment by mbi** [comment]
Fixed in 83b6571, thanks for the headsup
