### ISSUE TITLE
Let user propose translations using a django-inplaceedit -like mechanism

### ISSUE THREAD

**Issue by teolemon** [mbi/django-rosetta#144]
Let user propose translations using a django-inplaceedit -like mechanism:
The user loads a page, clicks on the content, translates from scratch or reviews the translation automatically generated by the system.
When he or she clicks outside the field, it is saved as a suggestion for an admin to review.

There should be an option to either display the automatically generated translation or the original text.
There should be an option where the user can +1 ou -1 an existing translation, in context.

**Comment by mbi** [comment]
This is about 101% orthogonal with the current feature set. It would make for a nice rewrite of the whole app, with all new features. And a new name.
