### ISSUE TITLE
API / External System Integration

### ISSUE THREAD

**Issue by jnosal** [mbi/django-rosetta#146]
Is there a way to integrate rosetta with other systems - we use django mainly for our "pure backend" tasks and dont expose cms for our client - for that we use wordpress. Is there a way we can easily integrate rosettas interface with that system - allow wordpress users to add/edit or delete stuff using some kind of api or widget or whatever ?

Another way would be to expose some custom django views and attach them via iframe but it seems unreasonable.

Any help/advice will be appreciated

**Comment by mbi** [comment]
Rosetta is just a relatively thin layer above [polib](https://bitbucket.org/izi/polib/wiki/Home). That'd be the closest you get to an API. Rosetta itself really isn't suited for doing that itself, I'm afraid.
