### ISSUE TITLE
Translation suggestions don't work

### ISSUE THREAD

**Issue by andrewjennings** [mbi/django-rosetta#15]
The "Suggestion" links within Rosetta no longer work.  When the user clicks on a Suggestion link, the text "Please use Translate v2. See http://code.google.com/apis/language/translate/overview.html" appears below the item the user attempted to translate.

This is because the Google Translate API v1 has been deprecated.  Version 2 is paid-only so something other than the google translate api must be used.

**Comment by SimonSteinberger** [comment]
Would be great, if you could switch over to Bing / Microsoft Translator. The API is very similar and easy to implement. MS Translator remains free for a rather big number of requests per day.

**Comment by mbi** [comment]
Switched the Bing's translation API. It's clearly not as clean and good as Google's API, but it's better than nothing I reckon.
