### ISSUE TITLE
icon_searchbox.png is missing

### ISSUE THREAD

**Issue by facconi** [mbi/django-rosetta#157]
Resource icon_searchbox.png (should be found in /static/admin/img/icon_searchbox.png) is missing from latest package.

```
Django==1.9.2
django-rosetta==0.7.8
```

**Comment by facconi** [comment]
Fixed in pull request django-rosetta/pull#158

**Comment by mbi** [comment]
Fixed via d135a1ae1a68d61aec938046b2cb86fb557b5384, thank you!
