### ISSUE TITLE
pip install fails with microsofttranslator 0.7 install error

### ISSUE THREAD

**Issue by maltebeckmann** [mbi/django-rosetta#159]
Just attempted to install django-rosetta via pip but the installation failed.
I am running Python 3.x on Ubuntu 14.04 LTS.

Can anyone reproduce this?

Collecting microsofttranslator>=0.7 (from django-rosetta)
  Using cached microsofttranslator-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hdlxuim1/microsofttranslator/setup.py", line 44, in <module>
        long_description=open('README.rst').read(),
      File "/home/django/.virtualenvs/django_project/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1133: ordinal not in range(128)

**Comment by mbi** [comment]
Hi Malte. I just [re-ran the tests](https://travis-ci.org/mbi/django-rosetta/jobs/109329948)  against a similar environment (Ubuntu 12.04 LTS, Python 3.5) and locally (OSX 10.11, Python 3.5.1) but I can't seem to reproduce this.

Is this on a fresh machine / VM, or has it been, uhm, _tampered_ with?

**Comment by maltebeckmann** [comment]
Hey thanks for your quick response -- it's a relatively fresh machine. Btw, I forgot to append the last part of the error message:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hdlxuim1/microsofttranslator

I just tried to install in another virtualenv and get the same result. Would you have any clue as to how I might get around this?

**Comment by mbi** [comment]
How do you reproduce this step by step?
Here is how I tested:

Booted up a new 14.04 LTS, then:
- `apt-get update && apt-get upgrade`
- `apt-get install python-virtualenv`
- `virtualenv --no-site-packages --python=python3.4 .venv`
- `source .venv/bin/activate`
- `pip install django-rosetta`

And this works fine.

**Comment by maltebeckmann** [comment]
Hi mbi!

I just spent some time digging into this, initially thinking this is Python 3.x related. Turns out that microsofttranslator seems to have an issue with locales if not properly set.

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = "en_US:en",
    LC_ALL = (unset),
    LC_CTYPE = "UTF-8",
    LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory

**Solution**
So all I did is add the following line to: /etc/default/locale
LC_ALL=“en_US.UTF-8"

That resolved the locale issue, subsequently the microsofttranslator install issue and Rosetta is properly installed now. I guess I should be posting that on the microsofttranslator.

How come none of you ran into this though? I did this with a vanilla installation of Ubuntu 14.04 with my locale set to en_US. This locale issue has occurred with Ubuntu 10.04, 12.04 and 14.04. I wonder when someone at Canonical decides to fix this.
