### ISSUE TITLE
After saving blog redirects to main and after i reload tab few times it redirects back to next blog

### ISSUE THREAD

**Issue by ArtemBernatskyy** [mbi/django-rosetta#172]
Use with: Django 1.9, NGINX, Gunicorn.

Tested on Chrome, Firefox x64 both on linux.
PS i also use django grapelli as admin theme.

Whole bug in reproduction. Visit main menu - click your app (i need to click double to enter)- than add translations (save) - redirects to main - after few page refreshes it redirects back to next blog.

PPS and when i use Chrome and visit rosetta from this url https://www.thecolornet.com/rosetta/pick/ than it works perfectly well. But in Firefox the problem described up is active.

**Comment by ArtemBernatskyy** [comment]
PS i also use django grapelli as admin theme.

**Comment by ArtemBernatskyy** [comment]
PPS and when i use Chrome and visit rosetta from this url https://www.thecolornet.com/rosetta/pick/ than it works perfectly well. But in Firefox the problem described up is active.

**Comment by mbi** [comment]
What is the content of your `settings.CACHES` and `settings.ROSETTA_*` (the ones you have overridden, if any)?

**Comment by ArtemBernatskyy** [comment]
Actually i haven't added such settings, but i think the problem is there because i am using 4 threaded gunicorn.

**Comment by mbi** [comment]
You must have something in `settings.CACHES` …?

**Comment by ArtemBernatskyy** [comment]
By default django uses `LocMemCache`, so i will try to change this to `memcache` and will notify you.

**Comment by mbi** [comment]
Ok, most definitely this, then: http://django-rosetta.readthedocs.io/en/latest/settings.html#storages

**Comment by ArtemBernatskyy** [comment]
Yes, thanks for your time.

**Comment by ArtemBernatskyy** [comment]
Yes, it works perfect now ! Thanks.
