### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by barseghyanartur** [mbi/django-rosetta#173]
- Which version of Django are you using?: 1.6.11
- Which version of django-rosetta are you using?: 0.7.4
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate? Yes

Usability is terrible. You can't put two locales next to each other and the language AFAIK is being set in a cookie. Either provide alternative to read language from URL (why redirect to home and why save language in cookie?) or make it possible to put two locales next to each other.

**Comment by gabn88** [comment]
I do agree that putting it in a url would be more clean, also when comparing languages. Terrible is maybe not the word, but I would too see it as an improvement.

**Comment by mbi** [comment]
I definitely agree the current status is far from pretty. There have been attempts to have a more restful (or at least cleaner) url structure, but in the end it just wasn't worth the time as the current status is ugly but works.

Note that you CAN put two locales next to each other, i.e. use another locale than en_\* as the source for the translation.

Anyway, I agree it's ugly as hell, patches are welcome as long as they are fully tested and documented 😏 but I am not going to sink time into this.
