### ISSUE TITLE
changeable messages file name

### ISSUE THREAD

**Issue by afaikafk** [mbi/django-rosetta#18]
The current code allows only 'django.po' files to be used, and as I found a way to use this helpful application in some non-fully django projects, it would be better if we could specify in our settings file at least for which filenames to look for.

**Comment by MattijnLahuis** [comment]
I'm replying to this (old) issue in the hopes of getting some clarification. I see that a settings has been added called ROSETTA_POFILENAMES, which supposedly solves this issue but I can't seem to get it to work. Is this issue solved at all yet?

**Comment by mbi** [comment]
Hi @MattijnLahuis, yes this is working. I just tried and sticked `ROSETTA_POFILENAMES = ('django.po', 'test.po')` in my settings.py and could edit a `test.po` file in Rosetta.

I'm closing this as it's indeed fixed, feel free to reopen if you feel this isn't working as you'd expect.
