### ISSUE TITLE
Reference language selector does not show up

### ISSUE THREAD

**Issue by egor83** [mbi/django-rosetta#180]
I set ROSETTA_ENABLE_REFLANG to True in settings, reloaded dev server, but nothing new showed up in Rosetta.

Django shell shows that setting itself is picked up by Rosetta:

    In [1]: from rosetta.conf import settings as rosetta_settings
    ...
    In [4]: getattr(settings, 'ROSETTA_ENABLE_REFLANG')
    Out[4]: True
    ...
    In [5]: getattr(rosetta_settings, 'ENABLE_REFLANG')
    Out[5]: True

Going directly to <TEST_SERVER>/rosetta/select-ref/en does nothing - navigates back to list of messages where it still shows raw msgid as source; going to <TEST_SERVER>/rosetta/select-ref/EN gives 404, as expected.

English and German translation files for the project are present and are shown in Rosetta, both languages are listed in `settings.LANGUAGES`.
We're using django-rosetta-grappelli2==1.1 if that matters.

I'd be happy to provide further information and/or run debug commands.

Thanks for the great project! It's been a great help for us.

----

- Which version of Django are you using?: 
1.8.13

- Which version of django-rosetta are you using?:
0.7.12

- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate?
Yes - searching for "reference language" gives two merged PRs and one unrelated issue; searching for "reflang" and setting name variations gives nothing.

**Comment by mbi** [comment]
Hm, I just tried (but failed) to reproduce this. 
Can you reproduce on a local development environment? (EDIT: i.e. with `python manage.py runserver`)

**Comment by egor83** [comment]
Looked a bit deeper - it was actually a problem with django-rosetta-grappelli, it rewrites a relevant portion of the menu; will add a ticket there. Sorry to bother.

But once that was figured out, I bumped into another problem, will add another ticket now.
