### ISSUE TITLE
Django-rosetta Doesn't work with django-jet admin style

### ISSUE THREAD

**Issue by mjrulesamrat** [mbi/django-rosetta#185]
- Django: 1.9
- django-rosetta: 0.7.12

I have installed `django-rosetta` and it was working fine untill I installed `django-jet==1.0.5`.
Now, Design is not rendering properly.

Have anyone faced same problem? 

![rosetta_bad](https://cloud.githubusercontent.com/assets/6413205/24544815/5973071a-1622-11e7-9ed5-402d501e5a70.png)

**Comment by mbi** [comment]
Rosetta uses the default vanilla Django admin templates and stylesheets, it's not surprising that integrating with a custom admin doesn't work. 

Closing because this isn't really a Rosetta issue, but if anyone hits this issue please feel free to suggest a solution.

**Comment by mjrulesamrat** [comment]
Sure. I guess, I have to go to django-jet for this issue.
Thanks anyways.
