### ISSUE TITLE
Strings with plural forms do not show up in search

### ISSUE THREAD

**Issue by egor83** [mbi/django-rosetta#186]
Searching Rosetta DB does not bring up strings that have both singular and plural forms; eg in the built-in German translation file for django.conf (django/conf/locale/de/LC_MESSAGES/django.po) searching for "woch" would only give two results ("Mittwoch" and "Keine Woche angegeben"), omitting the following:

    1038 #, python-format
    1039 msgid "%d week"
    1040 msgid_plural "%d weeks"
    1041 msgstr[0] "%d Woche"
    1042 msgstr[1] "%d Wochen"

--------------------

- Which version of Django are you using?: 
(1, 8, 13, 'final', 0)

- Which version of django-rosetta are you using?:
(0, 7, 12)

- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate?
Yes, searching for "plural" only gives two closed tickets.

**Comment by mbi** [comment]
I know, IIRC this is a limitation of polib.

**Comment by egor83** [comment]
Thanks Marco!

**Comment by mbi** [comment]
All credit goes to @jbaldivieso!
