### ISSUE TITLE
Update install instructions

### ISSUE THREAD

**Issue by josefnorlin** [mbi/django-rosetta#188]
Need to update install instructions a bit:

This doesn't work anymore since Django dropped patterns in Django 1.10:
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

Plus, I would suggest (since I'm new to Django) that it would be suggested to look at http://localhost:8000/rosetta (if this handler wasn't changed)

- Which version of Django are you using?: 1.10
- Which version of django-rosetta are you using?: 0.7.13
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues? utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate? yes

**Comment by decentral1se** [comment]
Looks like this can be closed off since #190 went it 👍

**Comment by mbi** [comment]
Yes indeed, didn't realize there was a dupe. Thanks!
