### ISSUE TITLE
Is it possible to not group identical strings into one translation?

### ISSUE THREAD

**Issue by Hamzehn** [mbi/django-rosetta#199]
Django Rosetta Version: 0.8.1

Hi, I tried searching the documentation and the list of issues for a similar question as this and couldn't find anything related to it.

Right now Rosetta (0.8.1) groups all occurrences of the same string into one translation input. This presents a problem in some languages that I would like to translate my project to, because even though the strings can (and ideally should) be identical in English, the slight change in context between where those occurrences are, requires them to be translated differently in other languages.

Is it possible to not have Rosetta group identical strings like this?

**Comment by TurnrDev** [comment]
This is an issue to django-admin / manage.py's `makemessages` command. (Probably more an issue with another underlying technology)

Have you tried adding context to your translations to see if that separates them?

**Comment by mbi** [comment]
Thanks @JayTurnr for stepping in. 

Jay is absolutely correct: Gettext (and Django) solve this problem with context strings which you can use in your templates and your Python code: the strings will appear separately in the Gettext catalog based on their context, and Rosetta should then handle them accordingly.

**Comment by Hamzehn** [comment]
Thanks guys!
