### ISSUE TITLE
Plural forms are broken for languages with more than two of them

### ISSUE THREAD

**Issue by rassie** [mbi/django-rosetta#2]
For example, Russian has three forms, however Rosetta fails to display input fields for all of them -- only two are shown. Even Rosetta's own translation has only two forms instead of three (https://github.com/mbi/django-rosetta/blob/develop/rosetta/locale/ru/LC_MESSAGES/django.po).

**Comment by mbi** [comment]
Yes, I reckon this is a big issue, but unfortunately I don't have the time or leisure to fix this. 
Contributions more than welcome, though!

**Comment by mbi** [comment]
Not sure how, why or when that happened, but this is actually fixed. Would you mind to confirm it works for you?
