### ISSUE TITLE
ROSETTA_ENABLE_TRANSLATION_SUGGESTIONS 404 not found

### ISSUE THREAD

**Issue by svdvonde** [mbi/django-rosetta#200]
When I enable translation suggestions via Azure (and enter my client id/secret key) the suggestions do not seem to work. When clicking 'suggest' the browser console throws a 404 error:

>  Not Found: /rosetta/files/project/fr/0/translate/

Note that I have not altered the error other than removing the GET parameters. Am I missing something?

- Which version of Django are you using?: **2.1**
- Which version of django-rosetta are you using?: **0.8.1**
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate? **Yes**

**Comment by mbi** [comment]
Sorry, this slipped under my radar, but it seems that the app we've been using the source translations from the Microsoft Translator Text API [no longer works](https://github.com/fulfilio/Microsoft-Translator-Python-API/issues/1).

We'll have to come up with another solution via the new Azure API. 

In the meantime, if you wish to enjoy free translation, the [Yandex API](https://tech.yandex.com/translate/) works fine.

**Comment by mbi** [comment]
Note to self: [new Azure API](https://docs.microsoft.com/en-us/azure/cognitive-services/Translator/quickstart-python-translate).

**Comment by svdvonde** [comment]
Thank you for the quick response! The reason I tried to go for Azure is because, after doing some completely unscientific experiments with some news articles, it appeared that Yandex's translation seems complete trash compared to the "hot new tech" in translation that's currently out there (DeepL translator is insane; haven't tested Azure's translation service). 

Could you point me to the location in the rosetta source code that is responsible for interfacing with the Azure API? Perhaps, if I'm feeling crazy some day, I can find the time to submit a pull request (if it does not involve me learning about the entire rosetta code base). 

Thank you!

**Comment by mbi** [comment]
Ha! that would rock :)

So it's really dead-simple, it all happens in [rosetta/views.py#L679](https://github.com/mbi/django-rosetta/blob/develop/rosetta/views.py#L679), you'd want to replace the few lines starting at line 695 with the snippet [here](https://docs.microsoft.com/en-us/azure/cognitive-services/Translator/quickstart-python-translate), but ideally use `requests` which is already a dependency instead of `http.client` and `urllib.parse`.

Cheers!

**Comment by mbi** [comment]
Thanks again for your support on this!
