### ISSUE TITLE
ROSETTA_REQUIRES_AUTH = False does not work, still requires login

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [mbi/django-rosetta#203]
- Which version of Django are you using?: 2.0.7
- Which version of django-rosetta are you using?: 0.8.3
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate? yes

**Comment by mbi** [comment]
Confirmed: the extra `login_required` in [rosetta/views.py#L58](https://github.com/mbi/django-rosetta/blob/develop/rosetta/views.py#L58) is the culprit :(

Would you consider submitting a pull-request?

**Comment by BarnabasSzabolcs** [comment]
Maybe later, I'm not sure how to properly fix this and submit a pull request to a foreign depo, quickly.
