### ISSUE TITLE
Wish: Change rosetta FUZZY admin column name for more descriptive.

### ISSUE THREAD

**Issue by orlra** [mbi/django-rosetta#206]
Long story short:
Column fuzzy is a nightmare to explain to someone who never used this tool.
it collides with fuzzy string matching which confuses devs who think string like '*login_error' will work for de_login_error, en_login_error, general_login_error etc.
Translators does not understand what fuzzy means in this context, and misuse or don't use at all.
Everybody around seems confused,, about it's `fuzzy` meaning and behaviour. Anything more descriptive as work-in-progress, incomplete or whatever naming is more precise would appear AT LEAST on admin side.

**Comment by mbi** [comment]
Well, for starters "fuzzy" is the official term [used by gettext](https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html) so changing it something else would confuse those users that do know what the term means in this context.

What would you suggest we used instead?

**Comment by orlra** [comment]
I'm fine with just admin column name as:

> incomplete / fuzzy

> fuzzy translation

> hidden / unused

as any name shown inside CMS. Even if we make slightly longer to be a little more descriptive than single word it will help more non-technical people to understand what is the meaning and how it can be used.  
Maybe tooltip or something can be used, I'm open to any ideas.
BTW. very useful tool :+1:

**Comment by mbi** [comment]
I added a tooltip, thanks for bringing this up.

![Screen Shot 2019-04-07 at 11 44 55](https://user-images.githubusercontent.com/131808/55681828-11e1fe80-592b-11e9-9b16-ba5e2c778e46.png)
