### ISSUE TITLE
Add ROSETTA_LANGUAGES setting

### ISSUE THREAD

**Issue by madEng84** [mbi/django-rosetta#219]
It would be useful to have the possibility to translate for a language that is not yet in the settings.LANGUAGES, because maybe the client wants to enable that language only after the translators have finished with their work

Maybe an approach like this could be very useful (row 8)
https://github.com/deschler/django-modeltranslation/blob/master/modeltranslation/settings.py
You could use the ROSETTA_LANGUAGES as variable name

**Comment by mbi** [comment]
Yes, I see how that would be an interesting feature! 

I was going to argue that for Django to process (create) the PO file in the first place, the language needs to be enabled in `settings.LANGUAGES`, but that's not actually true: you can e.g. `python manage.py makemessages -l ru` even though Russian is not enabled, and that'll happily create the PO catalog.

I'll give this a try at some point. Pull requests most welcome, of course!

**Comment by madEng84** [comment]
Yes, I know it, the problem is only that the other language is not visible in the admin panel

However, I hope I have time to contribute as soon as possible

**Comment by mbi** [comment]
Added this feature in 664b37e904b18d5dd10b448228e71bc47be74ad7

**Comment by madEng84** [comment]
Great! 
thanks a lot @mbi!

**Comment by mbi** [comment]
@madEng84 I'd really appreciate if you could test-drive this feature and give feedback!  e.g. `pip install https://github.com/mbi/django-rosetta/archive/develop.zip`

Cheers!

**Comment by madEng84** [comment]
It works @mbi 
When will you release it on pip?

Thanks a lot!

**Comment by mbi** [comment]
v0.9.3 was just released and contains this feature.
