### ISSUE TITLE
Percent sign does not get escaped?

### ISSUE THREAD

**Issue by schmilblick** [mbi/django-rosetta#22]
When i translate a text that contains a percent sign (see example below) I get fatal errors when trying to compile it. Rosetta doesn't seem to escape percent signs?

Original text: "Searches on the web with mobile devices have increased with 400% since last year."
Swedish translation: "Mobila sökningar har ökat med 400% det senaste året."

Error message from compilemessages:
/sv/LC_MESSAGES/django.po:1705: number of format specifications in 'msgid' and 'msgstr' does not match

And the translation module then throws the following error:
TypeError: %d format: a number is required, not dict

**Comment by mbi** [comment]
This is most likely a bug in gettext: you can reproduce the same behavior without using Rosetta, by e.g. 
1. generating the catalog with `python manage.py makemessages -a`
2. translating the code manually
3. running `python manage.py compilemessages`

It seems that gettext incorrectly sets the `python-format` flag on the message containing the percent sign. Removing the flag from the catalog fixes the issue. This should probably be adressed in gettext.

**Comment by mbi** [comment]
Looks like this bug was fixed in Django trunk some [7 weeks ago](https://code.djangoproject.com/ticket/11240), this should probably be ok when Django 1.4 is released.

**Comment by schmilblick** [comment]
Oops, I didn't see your replies until now, sorry!

Sweet, thanks!
