### ISSUE TITLE
"Unmatched variables" warning erroneously checks translator context hint

### ISSUE THREAD

**Issue by jeancochrane** [mbi/django-rosetta#237]
When translating a string, if the translator context hint uses string formatting syntax, the `blur` check will erroneously alert the user that there are unmatched variables in the string:

<img width="858" alt="Screen Shot 2020-05-20 at 10 17 26 AM" src="https://user-images.githubusercontent.com/14170650/82464613-e6b16480-9a83-11ea-8507-266c69a73858.png">

I believe this is because the `blur` check does not distinguish between the original message and its translator context:

https://github.com/mbi/django-rosetta/blob/1808edfca9ac07bfc282a8d2153f5e4566d1152f/rosetta/templates/rosetta/js/rosetta.js#L92-L95

I believe if we adjusted the `origs` selector `$('.original', $(this).parents('tr'))` to instead be `$('textarea').parents('tr').children('.original').children('.message')` we could be more specific about searching only the message and not the context. If this sounds right, I'd be happy to put together a quick PR.

Questions from the issue template:

- **Which version of Django are you using?**: 1.11.29.
- **Which version of django-rosetta are you using?**: 0.7.13, but looking at the `master` branch I believe the bug persists.
- **Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate?** Yes, I couldn't find anything referring to the `unmatched variable` error.

**Comment by mondeja** [comment]
I can reproduce it with master branch (v0.9.5).

**Comment by mbi** [comment]
Thanks @jeancochrane for reporting and @mondeja for the fix!
