### ISSUE TITLE
Why request some url `https://www.google.com/jsapi`

### ISSUE THREAD

**Issue by chenluyong** [mbi/django-rosetta#255]
- Which version of Django are you using?:  `Django 3.1`
- Which version of django-rosetta are you using?: `0.9.0`

Why do u request it `https://www.google.com/jsapi`.
This seems like an ugly request.
I don't see him contributing to the project itself.
He also slowed down the loading of web pages.
Because he's always making requests wrong.

**Comment by sarathak** [comment]
It is google chart js 

i don't know project using it or not 

https://developers.google.com/chart/interactive/docs/basic_load_libs

**Comment by mbi** [comment]
It's loading jQuery through the Google JS API. We could probably get rid of this and use Django's bundled jQuery. 
Pull requests more than welcome :hugs:
