### ISSUE TITLE
Plurals with context are rendered incorrectly

### ISSUE THREAD

**Issue by jieter** [mbi/django-rosetta#260]
With following `.po` excerpt, the context marker is rendered on top of the message id, as shown in the screenshot.
```
msgctxt "BADGE_PROGRESS_OBSERVATIONS"
msgid "1 observation"
msgid_plural "%{count} observations"
msgstr[0] "1 waarneming"
msgstr[1] "%{count} waarnemingen"
```

<img width="866" alt="Screenshot 2021-07-20 at 08 47 42" src="https://user-images.githubusercontent.com/1470389/126274593-d4a692c3-fa68-4b56-906e-0f03ed256dc9.png">

**Comment by jieter** [comment]
I had a look into this: vertical alignment of the msgid's with the textarea's is done using JavaScript here:

https://github.com/mbi/django-rosetta/blob/e095402daa9eca36db2a68c7be9ea24f826cf9be/rosetta/templates/rosetta/js/rosetta.js#L116-L122

**Comment by mbi** [comment]
Thanks. That JavaScript code is just ugly, I've moved the the context and comments into the last column, where they make more sense, and where we don't need any silly trickery to position them.

**Comment by jieter** [comment]
Great, thanks!

**Comment by jieter** [comment]
@mbi Can you indicate when this fix will be available in a release?

**Comment by mbi** [comment]
I don't really plan my releases, ... so here you go: [0.9.7](https://pypi.org/project/django-rosetta/0.9.7/), just released, contains this fix.

**Comment by jieter** [comment]
Thanks!
