### ISSUE TITLE
`re_path` is not available in django==4.0 anymore

### ISSUE THREAD

**Issue by jieter** [mbi/django-rosetta#264]
- Which version of Django are you using?: **django=4.0.0**
- Which version of django-rosetta are you using?: **0.9.7**
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate? **yes**

```
  File "/Users/jieter/.pyenv/versions/obs/lib/python3.9/site-packages/rosetta/urls.py", line 1, in <module>
    from django.conf.urls import re_path
ImportError: cannot import name 're_path' from 'django.conf.urls' (/Users/jieter/.pyenv/versions/obs/lib/python3.9/site-packages/django/conf/urls/__init__.py)
```

Using `from django.urls import re_path` is supported.

**Comment by jieter** [comment]
I see this is already correct in `master` as of this commit:
https://github.com/mbi/django-rosetta/commit/6c61ac8570012f07f307099d4306fcf5aa5cb3dd#diff-bd645e026a39000021abd5d3032124140b5f71677df1e3b3fc0812dbb854f461

It would be nice if this would be part of a release, django==4.0.0 was released yesterday.

**Comment by mbi** [comment]
Thanks for the heads-up, 0.9.8 just pushed to PyPi should fix this.

**Comment by jieter** [comment]
Great, thanks!
