### ISSUE TITLE
Export Django-rosetta translations

### ISSUE THREAD

**Issue by mrodriguezg1991** [mbi/django-rosetta#269]
Hello 
Our team is using Django-rosetta latest version on Django 3.2, we will like to have the option to export the site translation to an excel or word file,  Is there any options or ongoing develop to make this possible ?

**Comment by mbi** [comment]
I've used https://github.com/vint21h/django-po2xls/ and https://github.com/vint21h/django-xls2po/ for this and they works pretty well.
