### ISSUE TITLE
DeepL suggestions not working

### ISSUE THREAD

**Issue by rafaelromon** [mbi/django-rosetta#271]
Enviroment:
- Django==4.1.1
- django-rosetta==0.9.8

DeepL suggestions are no longer working, ajax response returns HTTP 403 Forbidden. I did some quick look through the documentation for the DeepL API and it seems sending the auth key in the post is no longer supported, it needs to be sent as a header see [documentation](https://www.deepl.com/docs-api/translate-text/translate-text/)

![error](https://user-images.githubusercontent.com/15263554/200654622-f6d17b95-170d-4664-96c1-9ed6523e2dc8.png)

**Comment by biermeester** [comment]
This can be resolved by adding the following header to the DeepL section in `rosetta.js`:

`"Authorization": "DeepL-Auth-Key {{rosetta_settings.DEEPL_AUTH_KEY}}"`

But then you start running into CORS issues, it seems. Looking into that at the moment.
