### ISSUE TITLE
Triple entries in local dev env on Mac

### ISSUE THREAD

**Issue by patroqueeet** [mbi/django-rosetta#272]
- Which version of Django are you using?:
- 3.2.*
- Which version of django-rosetta are you using?:
- 0.9.9
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate?
yes, so I did

issue: as of MacOS 12.3 https://discussions.apple.com/thread/251191099 it is not case sensitive anymore. running rosetta in a docker container hence displays each item 3 times for language variants.

settings:
```
LANGUAGES = global_settings.LANGUAGES + [("de-CH", _("Swiss German (informal)"))]
```

dir struct:
```
 $ ls  site/shareholder/locale
de    de_CH en
```

**Comment by mbi** [comment]
This is odd. We [already handle case insensitive filesystems](https://github.com/mbi/django-rosetta/blob/develop/rosetta/poutil.py#L76) when looking for PO catalogs, and AFAIK this works fine outside of a Docker container. 

Could you please test this running in a virtualenv directly in your Mac (i.e. not in a container)? Does the bug happen there, too?

**Comment by patroqueeet** [comment]
inside Mac terminal

```
>>> import os
>>> os.path.exists('site/shareholder/locale/de_Ch')
True
>>> os.path.exists('site/shareholder/locale/de_CH')
True
>>> import tempfile
>>> tmphandle, tmppath = tempfile.mkstemp()
>>> os.path.exists(tmppath.upper())
True
```

inside docker ubuntu

```
>>> import tempfile
>>> tmphandle, tmppath = tempfile.mkstemp()
>>> import os
>>> os.path.exists(tmppath.upper())
False
```

gives for app in docker:
<img width="1172" alt="Screenshot 2023-03-29 at 14 15 43" src="https://user-images.githubusercontent.com/2073086/228532622-92aaa97f-ac07-42b7-8a28-60a07d62e51a.png">

**Comment by mbi** [comment]
Relevant SO: https://stackoverflow.com/questions/64645430/why-does-mac-osx-still-exhibit-case-insensitivity-when-using-docker-desktop-for

**Comment by patroqueeet** [comment]
hm, good read. will not go for the SO options mentioned as I really like the mounts. will go with the 3 menus...

**Comment by patroqueeet** [comment]
FYI created a fork with a) allow vor `gettext` compliant variant def and b) definition of case sensitivity via settings:

https://github.com/mbi/django-rosetta/compare/develop...patroqueeet:django-rosetta:develop

now working well for me :)

**Comment by mbi** [comment]
Awesome. Is this contribution something that could be rolled up in a pull request and shared with the community? :)

**Comment by patroqueeet** [comment]
@mbi I can push a PR if you consider that worth it. I had the impression you would consider your case sensitivity automatic check superior.

will I have to provide tests?

**Comment by mbi** [comment]
I'm not considering it "superior", given it doesn't work in your case. Will both methods work alongside? Will your method detect and fix this particular usecase? And if it can be tested, then tests are welcome.
