### ISSUE TITLE
anyone can add chatgpt support?

### ISSUE THREAD

**Issue by ydf** [mbi/django-rosetta#275]
- Which version of Django are you using?: 3.2
- Which version of django-rosetta are you using?: last

**Comment by mbi** [comment]
PRs welcome as always. That said, I wonder how it could be any better / efficient / cost effective than specialized translation services such as Deepl.

**Comment by PaoloC68** [comment]
@mbi You are making a good point but the reality is this: I haven't a subscription to Deepl but I have one for openai, I would not mind to spend some tokens on translations but I would mind to open yet another a new subscription for maybe a single use.

**Comment by vusallyv** [comment]
https://github.com/mbi/django-rosetta/pull/291

**Comment by mbi** [comment]
Fixed via cf56dd3951ad03490651b7a0a5c45cc049f1a289, thanks @vusallyv
