### ISSUE TITLE
Chinese locale directory should be named 'zh_Hans' instead of 'zh_hans'

### ISSUE THREAD

**Issue by sunfkny** [mbi/django-rosetta#282]
Django won't discover 'zh_hans' https://github.com/django/django/blob/b287af5dc954628d4b336aefc5027b2edceee64b/django/utils/translation/__init__.py#L230-L243 so rosetta fallback to the default language. After renaming the directory to 'zh_Hans', the chinese translation works

**Comment by sunfkny** [comment]
My temporary workaround
```
import rosetta
import pathlib

rosetta_path = pathlib.Path(list(rosetta.__path__)[0])
rosetta_zh_hans_source_path = rosetta_path / "zh_hans"
rosetta_zh_hans_dest_path = rosetta_path / "zh_Hans"
if rosetta_zh_hans_source_path.exists():
    rosetta_zh_hans_source_path.rename(rosetta_zh_hans_dest_path)
```

**Comment by mbi** [comment]
Good catch, thank you!
