### ISSUE TITLE
Docs aren't up-to-date and don't work with latest django 

### ISSUE THREAD

**Issue by lc-thomas** [mbi/django-rosetta#286]
- Which version of Django are you using?
5.0.6
- Which version of django-rosetta are you using?
0.10.0
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate?
I did

Installing and configuring rosetta using the docs instructions fails with **urls.py** : 

```python
from django.conf.urls import include, re_path

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]
```

**ImportError: cannot import name 're_path' from 'django.conf.urls'**

I thought it had to be replaced by 'path' but I still cannot get it to work...

**Comment by lc-thomas** [comment]
Just found the solution, re_path still exists, it has just been moved from `django.conf.urls` to `django.urls`
So 
```python
from django.conf.urls import include, re_path
```
should be replaced with :
```python
from django.urls import include, re_path
```

**Comment by mbi** [comment]
Yea, the correct import should be 
```
from django.urls import include, re_path
``` 
Fixed, thank you.
