### ISSUE TITLE
Content-Security-Policy compatibility

### ISSUE THREAD

**Issue by bmihelac** [mbi/django-rosetta#287]
- Which version of Django are you using?:

Django 4.2

- Which version of django-rosetta are you using?:

0.10.0

- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate?
- 
Yes

---

It would be nice to ditch using inline styles and scripts so that the Django Rosetta admin interface can be used with [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) headers without needing to specify SHA-256 hashes.

The workaround for 0.10.0 is:

```python
CSP_STYLE_SRC += [
    "'sha256-q5rmgt0qnS6vusTX681CxP1llW8fGLSs67L4+dVXYgM='",
    "'sha256-r6dGmfJqBIB7bl4g+OioPKi2r6BGt6yJMK3smPY2W3o='",
    "'unsafe-hashes'",
]
CSP_SCRIPT_SRC += [
    "'sha256-+cShGZPBVbwcgDZxLez6BVyIIip5Ei8dtU08wGULPgA='",
    "'sha256-TcUB1mzXiQO4GxpTRZ0EMpOXKMU3u+n/q1WrgVIcs1I='",
]
```

**Comment by mbi** [comment]
Yea, I see that could be useful, although not my highest priority at the moment! A PR would be appreciated if you feel like digging into this.

**Comment by bmihelac** [comment]
@mbi  Thanks for suggestion. I’ll keep this in mind and see if I can find some time to work on it.

**Comment by mbi** [comment]
Merged, thank you so much!
