### ISSUE TITLE
user access to rosetta

### ISSUE THREAD

**Issue by snooopcatt** [mbi/django-rosetta#32]
task: 
user has to edit translations without access to admin interface
problem:
user has to be marked as superuser and staff ( http://code.google.com/p/django-rosetta/issues/detail?id=92 ), but this also grants user an access to admin interface. adding to group "translators" doesn't work as well

**Comment by mbi** [comment]
@ragzovskii The correct way is to add translators to the "translators" group, and NOT add mark them as either superuser nor staff.

**Comment by snooopcatt** [comment]
user wasn't in group 'translators' despite admin interface told other
