### ISSUE TITLE
Support for django==1.4

### ISSUE THREAD

**Issue by cypreess** [mbi/django-rosetta#33]
Using django 1.4 rosetta raises 
AttributeError at /rosetta/
'Settings' object has no attribute 'ADMIN_MEDIA_PREFIX'

ADMIN_MEDIA_PREFIX is now deprecated due to https://docs.djangoproject.com/en/dev/releases/1.4/#django-contrib-admin

**Comment by mbi** [comment]
Yup, thanks for the heads-up, this is fixed as of 0.6.6
