### ISSUE TITLE
Rosetta doesn't work with "feature url tag"

### ISSUE THREAD

**Issue by mokys** [mbi/django-rosetta#37]
I use "url" tag from feature library - in my settings.py file, there is:

import django.template
django.template.add_to_builtins('django.templatetags.future')

... and then rosetta says:

TemplateSyntaxError at /rosetta/
Could not parse the remainder: '-pick-file' from 'rosetta-pick-file'

**Comment by mbi** [comment]
Hmm, as far as I understand the "future" url tag is not backwards compatible, i.e. quoted named urls work with the future tag, but not the one coming with 1.3 / 1.4, or am I missing something? 

So unless there is a way to consistently support the url tag from version 1.2 trough 1.5 this is a no-go for me, until 1.5 is released.

**Comment by mokys** [comment]
Yes, I am sorry, you are right, that it would work in django 1.4 only.

What do you think about this solution:

Settings:
USE_FUTURE_URL = getattr(settings, 'ROSETTA_USE_FUTURE_URL', False)

Templates:
a href="{% if USE_FUTURE_URL %}{% url 'rosetta-pick-file' %}{% else %}{% url rosetta-pick-file %}{% endif %}"

That would be easy change on 6 places in templates.

**Comment by mbi** [comment]
Well, given that you seem to be the only one interested in this at the moment, you'd probably be better off forking and implementing this change yourself. I'll gladly accept a pull request if it covers documentation and tests, cheers!
