### ISSUE TITLE
Not working with signed_cookie session backend

### ISSUE THREAD

**Issue by SimonSteinberger** [mbi/django-rosetta#38]
Hi MBI,

I finally got the time to track down the bug I reported a while ago:

Rosetta is not working, when cookie-based sessions are enabled. That's a new session backend on Django 1.4:
https://docs.djangoproject.com/en/dev/topics/http/sessions/#using-cookie-based-sessions

Since you store the whole PO file in sessions, the cookie can easily exceed the common 4 kb limit and thus, simply gets deleted before it's processed. That's what happens in _all_ our projects. I don't know how big your PO files are or if you ever tested against the cookie-based session backend ... to enable and check this bug, add the following line to your settings.py:

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

Then _try_ selecting a reasonably sized PO file in Rosetta, that exceeds 4 kb.

p.s.
I fixed it by not writing the whole PO data into the session, but reading it directly from the PO file as needed. However, I assume, there will be issues, since you would have done that in the first place. I can send you the modified views.py if you like.

p.s.s.
Also, could you please add #toolbar {height:20px;overflow:hidden;} to your css style sheet. The layout bug is still there in FF 12.0, even if you can't see it: https://github.com/mbi/django-rosetta/issues/27

**Comment by askoretskiy** [comment]
Guys, please fix this issue -- it is not usable with this cool fast cookie-based sessions introduced in Django 1.4.

Moreover I found it cause Google Chrome to send too big headers that are rejected by stock installation of nginx.

**Comment by mbi** [comment]
@Nasmon @tonnzor I have just pushed a new branch which features pluggable storages to be used instead of the Django session backend (it defaults to Django's cache backend)

I'd really appreciate if you guys could test the branch and let me know if it fixes things for you.

**Comment by SimonSteinberger** [comment]
Thanks for your work! Really appreciated :) Nice idea to implement a separate storage system.

Maybe I'm doing something wrong: The branched version I just tested (https://github.com/mbi/django-rosetta/tree/storagesversion) does not appears to be complete. There is a basic Rosetta storage class inside the code, but it's not really used any further. Did I get the wrong version?

**Comment by mbi** [comment]
Fixed in 0.6.8.
