### ISSUE TITLE
Reload .po file

### ISSUE THREAD

**Issue by mjtorn** [mbi/django-rosetta#40]
If I add a new trans/blocktrans in a template, for example, it would appear there's no
way to get it into Rosetta without executing makemessages from the shell.

Could this be implemented?

**Comment by mbi** [comment]
Nope, sorry, this is completely out of scope: we really don't want to go into the business of updating the catalogs with new data, makemessages does an excellent job already.

**Comment by mjtorn** [comment]
Thanks for the reply!

This is something one hears about though, so maybe it would be helpful to write a little something on the reasoning. Is it common that makemessages would fail and the error is hard to represent and/or react upon? I can't see how, now, but that's a usual suspect :)
