### ISSUE TITLE
Language is duplicated in language selection

### ISSUE THREAD

**Issue by sneawo** [mbi/django-rosetta#47]
I have zh-cn in languages

```
LANGUAGES = (
    ('en', gettext('English')),
    ('zh-cn', gettext('Mandarin Chinese')),
)
```

In mac os file system is case insensitive and on the language selection page I'm getting two rows with files
/locale/zh_CN/LC_MESSAGES/django.po
/locale/zh_cn/LC_MESSAGES/django.po

**Comment by ricobl** [comment]
The same for me!

Some debugging lead me to the`rosetta.poutil.find_pos` function.
It searches for locale dirs and installed apps to build possible paths for `.po` files for a language and then tests if those files exist.

In my case, the problem also seems to be with the [HFS filesystem, which is case-insentive by default](http://bytes.com/topic/python/answers/441007-filename-case-insensitivity-os-x), making `os.path.isfile` return true for any case combination.

My suggestion as a workaround would require to use something like `os.listdir` or `glob.glob` on each locale dir and test against the desired language name patterns.

Looks like it's [possible to convert the filesystem to case-sensitive HFS](http://reviews.cnet.com/8301-13727_7-10343413-263.html), but I think it isn't worth the trouble.

**Comment by maltebeckmann** [comment]
I am still having this issue. I am getting:

/locale/zh_HANS/LC_MESSAGES/django.po
/locale/zh_Hans/LC_MESSAGES/django.po
/locale/zh_hans/LC_MESSAGES/django.po
