### ISSUE TITLE
Move from Bing to Azure for translation suggestions

### ISSUE THREAD

**Issue by SimonSteinberger** [mbi/django-rosetta#48]
Microsoft Translator API has moved to Azure DataMarket. I believe, currently the Bing API is still working despite Microsoft's announcement of terminating the service as of August 1st, 2012. Not sure about that, but it's probably a good idea to move to Azure ... it's actually just changing a few lines of codes and introducing two new values as a replacement for BING_APP_ID in settings.py.

Here's how to use Microsofts translator on Azure:
https://github.com/openlabs/Microsoft-Translator-Python-API

Kind regards

**Comment by davidkuchar** [comment]
This is a breaking issue for me, they don't make BING_APP_IDs anymore.

**Comment by davidkuchar** [comment]
I forked and refactored this:

https://github.com/davidkuchar/django-rosetta

**Comment by espenak** [comment]
I would love to see this merged into the main repo. Is there any plan to do so, or another solution for translation suggestions?

**Comment by suhailvs** [comment]
why this is not merged with the main repo?? is bing still working???

**Comment by mbi** [comment]
Maybe @davidkuchar wants to submit a pull request of his changes? 

As soon as we have some working code, with some documentation changes and maybe a test or two I'll gladly merge this, cheers.

**Comment by maikelwever** [comment]
Well, I've merged @davidkuchar his fork of this project with the current develop branch.
I've tested it briefly, and updated the readme to reflect the changes.

I will submit a pull request, but note that all changes are not mine.

**Comment by svdvonde** [comment]
@mbi  this seems like a really old (now irrelevant) issue too

**Comment by mbi** [comment]
Yes, closing too, thanks. (fixed in #200 / 0.8.3)
