### ISSUE TITLE
Use of messages variable causes conflict in django messages framework

### ISSUE THREAD

**Issue by scaryclam** [mbi/django-rosetta#5]
Hi,

we use the django messages framework to pass notices to pages in our website. Unfortunately rosetta uses the local variable messages (line 200 in views.py). Due to the variable being named "messages" and the variable being returned in the response context we've found that the messages framework gets trodden on.

Would it be possible to use a different name for this variable in views.py (and pofile.html)?

**Comment by mbi** [comment]
Not sure I understand the issue here: the `message` variable is local to the context of Rosetta, and is displayed in an isolated manner inside a Rosetta template, how would if affect your message framework?

**Comment by scaryclam** [comment]
We were customising the rosetta template to fit in with the look and feel of our website by putting it into the local project under templates/rosetta. Because rosetta uses "messages" as the variable name, the usual messages framework is unusable for any of the customised rosetta templates.

We're now using a patched version of rosetta (changing "messages" to "rosetta_msgs") which allows rosetta and the django messaging framework to co-exist properly.

The issue is simply the use of the variable name "messages" when integrating rosetta into websites that also make use of django messages to convey information back to users.

Hope that makes the issue clearer.

**Comment by mbi** [comment]
Okay, I hope you'll agree this isn't an issue with Rosetta then, and probably best taken care of in a fork.

**Comment by scaryclam** [comment]
It seems more of a naming issue to me. The messages variable name is part of django. Would it not just be possible to use a variable such as rosetta_messages rather than conflicting with django? It's only used in two places and anyone who uses django messages and rosetta will get this issue.

**Comment by mbi** [comment]
Anyone who uses Rosetta embedded into the global admin, you mean? Or am I missing something again? 
Anyway, I'll accept a pull request that addresses this issue, as long as it's fully tested.

**Comment by scaryclam** [comment]
It can affect anyone just trying to use the messages framework in their site alongside rosetta that has been edited to fit in with their look and feel. Basically, the home() view in views.py puts locals() into the context. Djangos messages framework also uses the messages variable name. So when a project puts something like:

<pre>
{% if messages %}
&lt;ul class="messages"&gt;
    {% for message in messages %}
    &lt;li{% if message.tags %} class="{{ message.tags }}"{% endif %}&gt;{{ message }}&lt;/li&gt;
    {% endfor %}
&lt;/ul&gt;
{% endif %}
</pre>


into a template like base.html, django messages spits out all of the rosetta languages stored in the messages variable onto the page. So the project must either copy the above code into every template where they might want to see messages appear (tedious for even a medium project) or patch rosetta to use a less general variable name.

I've make a fork and applied some changes but am wondering if you have any specific tests for templates. If not I'll set up a test project and make sure it all works as expected before making a pull request.

Thanks,

Becky Lewis
