### ISSUE TITLE
Displays application twice when using a language code with an underscore

### ISSUE THREAD

**Issue by dlo** [mbi/django-rosetta#52]
I have a PO directory called en_US. In the admin panel, rosetta displays both en_US and en_us. Only editing en_us does any actual updates to the translation files.

**Comment by jgsogo** [comment]
Same problem here, but I see three files for each:

![image](https://cloud.githubusercontent.com/assets/1406456/16922674/e72909e0-4d16-11e6-9315-170222011a84.png)

Development server on **Win7-64bits**, python 2.7, django 1.9

**Comment by dlo** [comment]
Wow...talk about a long-standing bug. Totally forgot about this. 😜

**Comment by faxioman** [comment]
Same here with django 1.9

**Comment by marcmoore** [comment]
Hi there. Is there anyone fix this issue?
