### ISSUE TITLE
local dir in project root is ignored

### ISSUE THREAD

**Issue by tijs** [mbi/django-rosetta#63]
I use one project wide locale/ directory in the project root (same dir as manage.py) but i am unable to get rosetta to detect these localisation files. I've tried both the stable and develop (0.7.0) release and both show the django and third-party messages in the overview but the project overview just says "Nothing to translate!".

**Comment by tijs** [comment]
This looks to be an issue with project layout. I tend to have my project layout as follows (following django 1.4 defaults):

```
project_root/
    manage.py
    core_app/settings.py
    locale/
        en/
        fr/
    some_app/
```

In this setup i can run makemessages from the root and have it create po files for each app in the main locale dir.

rosetta on the other hand considers the directory containing the settings file to be the project root and thus fails to find the locale directory. A simple patch would be to simply check both directories?

**Comment by mbi** [comment]
Hi, thanks for the PR. I've just pushed a slightly more robust version of your patch, would you mind testing and see if this works for you?

**Comment by tijs** [comment]
yes, awesome! works like a charm.

**Comment by mbi** [comment]
Awesome, thanks for the heads-up
