### ISSUE TITLE
Please upload 0.7.0 to PyPI, Django 1.5 is broken with current PyPI version

### ISSUE THREAD

**Issue by dyve** [mbi/django-rosetta#66]
PyPI has 0.6.8 which doesn't work with Django 1.5. Please upload 0.7.0 to PyPI.

**Comment by mbi** [comment]
Sure, just pushed 0.7.0

**Comment by mbi** [comment]
scratch that, just pushed 0.7.1

**Comment by dyve** [comment]
Thanks, appreciate it

## 

Sent from my iPhone

Op 1 mrt. 2013 om 11:45 heeft Marco Bonetti notifications@github.com het volgende geschreven:
