### ISSUE TITLE
Fail on unicode appname.

### ISSUE THREAD

**Issue by Christophe31** [mbi/django-rosetta#67]
I had this error thrown on  rosetta/poutil.py line 76

app = getattr(**import**(appname[:p], {}, {}, [appname[p + 1:]]), appname[p + 1:])
TypeError: Item in ``from list'' not a string

I'm French and I use in my settings.py. I use python 2.7/2.6
    from **future** import unicode_literals

I found how to fix it with this stackoverflow answer:
http://stackoverflow.com/a/2683624/267364

So, putting a b prefix to have non unicode appname look required for this application to work for python 2 when the rest of django's environnement is ok. maybe you may want to user an str cast on appname to fix it. (will work with both unicode and non unicode appname for python 2, and probably python 3 as import should take unicode literals.)

**Comment by mbi** [comment]
Salut.

> unicode appname.

Wait, what? I wasn't avare Django supported unicode appnames. How will this behave with DB tablenames, directory names and so on?

**Comment by Christophe31** [comment]
sorry, my appnames are ascii but they are declared as unicode literals in INSTALLED_APPS.

And there are no problems.

**Comment by mbi** [comment]
Oh I see. Out of sheer curiosity, what is the advantage of doing so?
(apart discovering interesting bugs in third party apps)

**Comment by Christophe31** [comment]
As I'm French I use a lot of accentuated characters (éèàêç...) and I have some strings in my settings.

I had read that django want to be full unicode. everything is meant to be displayed or used as unicode. So it will reduce auto casting of string to have all in unicode. It looks cleaner to me to not mix string types.

Some strings are meant to be displayed in my settings (or used as emails content base).

May be my case is uncommon but I suppose Japanese peoples and other language where every word is made of UTF8 characters had taken the habit to generalize Unicode with the **future** import.

As a simple "é" in a string without the Unicode prefix make the application crash, i use it everywhere without even thinking about it. (admin names, passwords, custom strings ...)

My usecase may be really uncommon but i hope if somebody have it, he will find my troubleshooting here.

**Comment by mbi** [comment]
That's quite alright! I work in a french-speaking environment too, and most of the websites I develop have a french locale but I wouldn't have thought of using unicode literals in app names.

This is a valid bug, I'll try to reproduce and fix this when I get a chance.

**Comment by mbi** [comment]
Okay this is fixed in HEAD, cheers.
