### ISSUE TITLE
module named six

### ISSUE THREAD

**Issue by kuyucakli** [mbi/django-rosetta#72]
Hello i am using django 1.5 with custom auth. I have installed development branch of rosetta in order to use it with django 1.5.
I am getting module named six error when try to reach http://127.0.0.1:8000/rosetta/

**Comment by mbi** [comment]
Hi, what is the error, and how did you install Rosetta?

**Comment by kuyucakli** [comment]
This is the only error info:
import six
ImportError: No module named six
I have downloaded the development version, copy the rosetta folder to my projects root , and add it into installed applications.

**Comment by mbi** [comment]
I see. You'll have to install via pip or easy_install,
That'll also pull the dependencies. 

I.e pip install django-rosetta
