### ISSUE TITLE
Option to hide file name & path - feature request 

### ISSUE THREAD

**Issue by rtpm** [mbi/django-rosetta#77]
For security reason it would be great if there was an option to not display information about the file the string is used in. (both file & full path).

This would be useful if you deletage translating to some external company/translator.

Thanks

**Comment by mbi** [comment]
Right, this should be quite easy to implement, please include a test if you're planning to submit a pull request!

**Comment by mbi** [comment]
Fixed via #221, thanks @sarathak!
