### ISSUE TITLE
Urls reversing not working on Django 1.5.1

### ISSUE THREAD

**Issue by guillaumepiot** [mbi/django-rosetta#78]
The url reverse in Django 1.5.1 is now in the format {% url 'app:url_name' %}, which is not compatible anymore with the current Rosetta templates.

Error is the following:

`TemplateSyntaxError: Could not parse the remainder: '-pick-file' from 'rosetta-pick-file'. The syntax of 'url' changed in Django 1.5, see the docs.`

Any chance this could be updated to Django 1.5.1?

**Comment by mbi** [comment]
Which version of Rosetta, and which template file and line is this?  

Thanks.   

##

**Comment by guillaumepiot** [comment]
The error is actually occuring on line 27 in base.html:

`<h1 id="site-name"><a href="{% url 'rosetta-pick-file' %}">Rosetta</a> </h1>`

Though, it looks correct, Django seems to be looking for something in the format 'rosetta:pick-file', very strange

**Comment by guillaumepiot** [comment]
After further investigation, the error happens to be on my side, so all clear for me.

**Comment by caumons** [comment]
@guillaumepiot please close this issue! :)
