### ISSUE TITLE
Tests modify global state (settings.LANGUAGES) and don't restore original state after run

### ISSUE THREAD

**Issue by zsoldosp** [mbi/django-rosetta#81]
This causes issues with test isolation - if I were to run my application's business test in the same run as rosetta's tests, I would have my application's tests failing that may rely on the settings.

The offending line is in RosettaTestCase.setUp (https://github.com/mbi/django-rosetta/blob/44b3314fd4eac955be18f745e28c9d874d1c9ac2/rosetta/tests/__init__.py#L53) 

The way I usually address these issues is by storing the original value of the setting my tests modify, and then restore them in the tearDown method

**Comment by mbi** [comment]
Yes, good catch, I'll fix this pronto.

**Comment by mbi** [comment]
Fixed, thanks for the heads-up!
