### ISSUE TITLE
rosetta_i18n_catalog_filter in languages.html is always empty

### ISSUE THREAD

**Issue by kunitoki** [mbi/django-rosetta#87]
there is a {% ifequal rosetta_i18n_catalog_filter 'something' %} in languages.html template, but the variable is not defined in the context, so the active button highlight doesn't work.

**Comment by mbi** [comment]
Good catch, thank you, I'll fix this pronto.

**Comment by mbi** [comment]
Fixed in bf0b253dec72e3a26098e0568fdeab3bc840fa3b, thank you.
