### ISSUE TITLE
rosetta writes empty string to po file

### ISSUE THREAD

**Issue by malik-vxt** [mbi/django-rosetta#88]
Hi,

When save some transaltions rosetta ads the folowing to to the po file.

msgid ""
msgstr ""
"Project-Id-Version: Django Test\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-05-28 13:53+0200\n"
"PO-Revision-Date: 2013-08-21 13:02+0000\n"
"Last-Translator:   mail@example.com\n"
"Language-Team: This that mail@example.com\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: \n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"X-Poedit-Country: FRANCE\n"
"X-Poedit-Language: French\n"
"X-Poedit-SourceCharset: utf-8\n"
"X-Translated-Using: django-rosetta 0.7.2\n"

Which in the end make the translation of any empty string into the above text , is this bug or the expected behavior ?

**Comment by mbi** [comment]
Hello, maybe I'm missing something, but that is a standard Gettext PO header, e.g. http://codex.wordpress.org/Translating_WordPress#The_PO_File_Header 

AFAIK you shouldn't have empty strings marked for translation in your source in the first place (why would you?). 
One solution would be to mark the empty string in the header as fuzzy, as in the example above.

**Comment by malik-vxt** [comment]
Hi,
First thanks for the update and the link, the reason for why I have empty strings is due to the fact I try to translate database-stored string.
