### ISSUE TITLE
Although locales are found, I can't open them. 

### ISSUE THREAD

**Issue by xpanta** [mbi/django-rosetta#92]
Hi,

I have installed rosetta, I am using django 1.4.5. At first I could not open the rosetta panel because /rosetta/ url redirected me to /accounts/login/ (although my admin user had already been logged in through the admin panel, and I am using /login/ instead of /accounts/login/ to authenticate).

So, I had to add ROSETTA_REQUIRES_AUTH = False in my settings.py file. After this, rosetta panel opened. However I only see something like this.

https://dl.dropboxusercontent.com/u/2423935/ros.JPG

and whenever I click on 'conf' it doesn't do anything.

What am I doing wrong?

Any ideas what should I do?

PS: I have added my admin user to the translators group, too (although it is not necessary) and admin user is always logged in.

**Comment by mbi** [comment]
I suspect a general configuration problem.  

First off, which version of Rosetta, which web server (development server, nginx+gnuicorn, Apache+mod_wsgi,…) and what is in your CACHES setting, please?  

## 

Marco Bonetti
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by xpanta** [comment]
Thanks for the prompt reply. 

Latest rosetta (0.7.2)
Apache+Nginx
These are my cache settings:

CACHES = {
     'default': {
          'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
          'LOCATION': 'unix:/home/xpanta/memcached.sock',
      }
}

ROSETTA_MESSAGES_PER_PAGE = 50
ROSETTA_REQUIRES_AUTH = False
BING_API_ID = '<id>' 

LANGUAGE_CODE = 'en-us'
gettext = lambda s:s
LANGUAGES = (
    ('el', gettext('Greek')),
    ('en', gettext('English')),
    ) 

LOCALE_PATHS = (
     '/home/xpanta/webapps/proj/proj/proj/conf/locale/',
     )

**Comment by intellisense** [comment]
I am also experiencing this same issue. None of the links are actually working for me. It works for sometime and all of sudden none of urls on click takes me anywhere keep me on rosetta index page. I am also using latest rosetta version on ubuntu + apache and i am not using any cache.

P.S. i got this error just now when i tried to open a language file:

```
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/rosetta/views.py", line 375, in lang_sel
    file_ = sorted(find_pos(langid, project_apps=project_apps, django_apps=django_apps, third_party_apps=third_party_apps), key=get_app_name)[int(idx)]

IndexError: list index out of range
```

**Comment by xpanta** [comment]
Hi, I think I found where the problem lies. In views.py line 56 it says:

if storage.has('rosetta_i18n_fn'):

This returns false. So the code inside is never run. What is storage and how can add rosetta_i18n_fn in it?

**Comment by xpanta** [comment]
Locally, rosetta works. At my development PC I use django 1.4.2, at my production PC (where rosetta doesn't work) I use django 1.4.5. Hope that helps.

**Comment by mbi** [comment]
Which webserver / app-server, and what is your CACHES on production?

**Comment by xpanta** [comment]
It is the configuration I already described. I haven't changed anything since then. 
https://github.com/mbi/django-rosetta/issues/92#issuecomment-28466211

at my development PC I don't use any cache framework and I use standard django dev server.

**Comment by intellisense** [comment]
I am not using any cache server on the production as well. Is it mandatory to use any cache service or it is just recommended/optional? I am using latest version of rosetta and django 1.4.3 with python 2.7+

**Comment by mbi** [comment]
Yes: proper CACHES is required on production (with a multi-threaded server). See the warning under Storages in the README.
