### ISSUE TITLE
Bing translate suggestion no longer works

### ISSUE THREAD

**Issue by chrisspen** [mbi/django-rosetta#93]
The Bing translate service appears to have moved to the Azure platform, and now there doesn't seem to be any clear way to get a "BING_APP_ID". I tried using my "account key" but the suggest feature reports the error:

```
ArgumentException: Invalid appId
Parameter name: appId : ID=3802.V2_Json.Translate.2A1BE722
```

**Comment by mbi** [comment]
Yes, this is addressed by issue #86. The way to go will probably be to fork Microsoft-Translator-Python-API and distribute it with Rosetta

**Comment by svdvonde** [comment]
@mbi this issue seems no longer relevant

**Comment by mbi** [comment]
Correct, closing, thanks
